### ISSUE TITLE
Connect Redux not working

### ISSUE THREAD

**Issue by rockchalkwushock** [EQuimper/VSC-React-Native-React-Redux-Snippets#1]
I've uninstalled and reinstalled but still am getting the same issue:

`ccr` does not populate as an option in my shortcuts.

All other options on the package are working fine.

**Comment by EQuimper** [comment]
Thank you @rockchalkwushock gonna look at this one + add some new one :)

**Comment by EQuimper** [comment]
@rockchalkwushock all work now but now this is `crr` :)
