### ISSUE TITLE
How to get constructor method also in ccs ?

### ISSUE THREAD

**Issue by ghost** [EQuimper/VSC-React-Native-React-Redux-Snippets#12]
i want 
```
constructor(props) {
    super(props);
    this.state = {  };
  }
```
instead of 
`state = {  };`
when i type ccs, how can i get it ?

**Comment by EQuimper** [comment]
I’m gonna create a second version with the constructor. Gonna be call with cccs this is good for you ? :)

**Comment by EQuimper** [comment]
@sushmit-oodles Done just upload to version 1.6.0 :)

**Comment by EQuimper** [comment]
https://github.com/EQuimper/VSC-React-Native-React-Redux-Snippets#cccs-component-class-with-constructor

**Comment by ghost** [comment]
Amazing thanx a alot mate. :)
Can i suggest more snippets in future if i come up with some new ideas if
you dont mind ?

**Comment by EQuimper** [comment]
Yes sure :)
