### ISSUE TITLE
add PropTypes snippets

### ISSUE THREAD

**Issue by selrond** [EQuimper/VSC-React-Native-React-Redux-Snippets#13]
Have you considered adding snippets for prop-types?

**Comment by douglasjunior** [comment]
+1

**Comment by EQuimper** [comment]
I'm open to merge a pr here, I dont use propTypes I use flow.

**Comment by selrond** [comment]
@douglasjunior I'm thinking about creating VSCode snippets just for PropTypes - as it's not tightly bound to React.

Would you be in for a collaboration?

**Comment by douglasjunior** [comment]
https://github.com/EQuimper/VSC-React-Native-React-Redux-Snippets/pull/7

**Comment by EQuimper** [comment]
#7 is already add, this is on version 1.7.3
