### ISSUE TITLE
issue with the component name  

### ISSUE THREAD

**Issue by undrafted** [EQuimper/VSC-React-Native-React-Redux-Snippets#16]
I'm facing a weird issue and i'm not sure if its specific to my setup - but the components names are weirdly capitalized. Here's for my **ProductCard.js**

<img width="330" alt="screen shot 2019-01-15 at 10 07 59 am" src="https://user-images.githubusercontent.com/17349825/51161875-92094280-18ad-11e9-8f8e-02c009c908e3.png">

**Comment by EQuimper** [comment]
Umh weird, I will take a look this afternoon. Been using it for the past month before I put it in the snippets here. Look like I didnt test everything. So the file was ProductCard.js from the beginning no rename ?

**Comment by undrafted** [comment]
Yeah - no rename, & happens for all the component initialization snippets. I'll also have a look if its specific to my setup. Thx

**Comment by EQuimper** [comment]
@undrafted Just published version 2.0.1 let me know if that fix it plz

**Comment by undrafted** [comment]
Works perfectly now 🥇 thank you @EQuimper
