### ISSUE TITLE
Setting to disable semicolons

### ISSUE THREAD

**Issue by danieljvdm** [EQuimper/VSC-React-Native-React-Redux-Snippets#3]
Can we have this as a configuration option?

**Comment by EQuimper** [comment]
Yes I need to check a way to make it. Do you have an idea for it ? Cause now the only way should be an other version but for standard

**Comment by EQuimper** [comment]
@danieljvdm Have create this extensions for the no semicolon :) https://github.com/EQuimper/VSC-React-Native-React-Redux-Snippets-Version-Standard
