### ISSUE TITLE
Customise snippet for console.log

### ISSUE THREAD

**Issue by Manish-Giri** [EQuimper/VSC-React-Native-React-Redux-Snippets#8]
Is there a way to customise the [snippet](https://github.com/EQuimper/VSC-React-Native-React-Redux-Snippets#log-console-log) for `console.log` to remove the `===`s at the top and bottom?

```
console.log('====================================');
console.log($1);
console.log('====================================');
```

**Comment by EQuimper** [comment]
@Manish-Giri if you try `cl` this is gonna give `console.log()`
